/**:
  ros__parameters:
    plugin_lib_names:
      - BT_cb_run_pose_estimation_action
      - BT_cb_prepare_single_block_request_action
      - BT_cb_plan_and_compute_trajectory_action
      - BT_cb_execute_trajectory_action
      - BT_cb_move_to_named_configuration_action
      - BT_cb_get_next_assembly_task_action
      - BT_cb_set_block_task_status_action
      - BT_cb_gripper_action
    behaviortree: "install/concrete_block_behavior_tree/share/concrete_block_behavior_tree/behavior_trees/concrete_block_assembly.xml"
