/**:
  ros__parameters:
    plugin_lib_names:
      # epsilon_crane_behavior_tree
      - BT_set_goal_pose_bt_node
      - BT_calc_a2b_movement_bt_node
      - BT_wait_goal_pose_decorator
      - BT_optimize_target_angle_bt_node
      - BT_get_user_approval_decorator
      - BT_check_user_approval_condition
      # lsrl_behavior_tree
      - BT_follow_joint_trajectory_action
      - BT_switch_controller_action
    behaviortree: "move_empty.xml"
