package: concrete_block_behavior_tree
behavior_trees:
  - name: "Basic pick and place"
    path: "/behavior_trees/basic_pick_and_place.xml"
  - name: "Wall assembly"
    path: "/behavior_trees/wall_assembly.xml"
  - name: "Move empty (A2B to RViz goal)"
    path: "/behavior_trees/move_empty_pzs100.xml"
  - name: "CBS move empty (A2B to RViz goal, new stack)"
    path: "/behavior_trees/cbs_move_empty_pzs100.xml"
