/**:
  ros__parameters:
    bt_loop_duration: 100
    always_reload_bt_xml: true
    plugin_lib_names:
      - BT_cb_run_pose_estimation_action
      - BT_cb_plan_geometric_path_action
      - BT_cb_compute_trajectory_action
      - BT_cb_execute_trajectory_action
      - BT_cb_move_to_named_configuration_action
      - BT_cb_get_next_assembly_task_action
      - BT_cb_set_block_task_status_action
      - BT_cb_gripper_action
    behaviortree: "install/concrete_block_behavior_tree/share/concrete_block_behavior_tree/behavior_trees/concrete_block_assembly.xml"
    logging:
      enable_groot_monitoring: true
      enable_file_logging: true
      enable_cout_logging: true

lifecycle_manager:
  ros__parameters:
    autostart: true
    node_names: ["bt_action_server"]
    bond_timeout: 4.0
    attempt_respawn_reconnection: true
    bond_respawn_max_duration: 10.0
